version: '3'
services:
  nestjs-api:
    container_name: nestjs-api
    image: nestjs-api
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./database:/user/src/app/database
    # restart: unless-stopped
